import { getDb } from "./index";
import { books, journalEntries } from "./schema";

const now = new Date().toISOString();

const seedBooks = [
  {
    id: "book-howling-dark",
    title: "Howling Dark",
    author: "Christopher Ruocchio",
    genres: JSON.stringify(["Fantasy"]),
    rating: null,
    status: "reading",
    readingMood: "captivating",
    startDate: "2026-03-25",
    finishDate: null,
    currentPage: 0,
    totalPages: null,
    pdfPath: null,
    coverImageUrl: null,
    isbn: null,
    journalEntry: "Mid-read, chapter 10. This chapter is called Jinan and it's basically Hadrian trying to have an argument with the woman he loves but being too scared to actually have it.",
    keyLessons: JSON.stringify([
      "Loving someone doesn't mean they'll see things your way",
      "Intimacy isn't the same as loyalty or agreement",
      "Sometimes the most honest thing someone can do is stay present with you instead of making promises they can't keep",
    ]),
    favoriteQuotes: JSON.stringify([
      "It was fear I felt, not anger.",
      "It did not last, nor did I. It could not last. But nothing is beautiful because it lasts.",
      "Do you really think I would let them take you from me?",
    ]),
    aiDiscussion: "Discussion Prompts for \"Howling Dark\": 1. Exploration of Darkness 2. Character Development 3. Philosophical Questions 4. Quotes and Reflections 5. Connections to Modern Times 6. Personal Insights",
    aiRecommended: 1,
    place: null,
    createdAt: "2026-03-25T01:00:00.000Z",
    updatedAt: "2026-03-28T16:16:00.000Z",
  },
  {
    id: "book-abolition-of-man",
    title: "The Abolition of Man",
    author: "C.S. Lewis",
    genres: JSON.stringify(["Philosophy", "Non-fiction", "Classics"]),
    rating: 5,
    status: "to-read",
    readingMood: "thought-provoking",
    startDate: "2026-04-16",
    finishDate: "2026-04-18",
    currentPage: 0,
    totalPages: 113,
    pdfPath: null,
    coverImageUrl: null,
    isbn: null,
    journalEntry: "Lewis's defense of objective value and natural law. Essential reading for understanding debates about moral relativism and the foundation of ethics.",
    keyLessons: JSON.stringify([]),
    favoriteQuotes: JSON.stringify([]),
    aiDiscussion: "Discussion Prompts: 1) Is Lewis right that rejecting objective values leads to the abolition of humanity? 2) How does the Tao compare to modern ethical frameworks? 3) What are naturalistic responses to his critique? 4) How does this connect to contemporary debates about moral realism?",
    aiRecommended: 1,
    place: null,
    createdAt: "2026-03-25T00:25:00.000Z",
    updatedAt: "2026-03-26T02:17:00.000Z",
  },
  {
    id: "book-mere-christianity",
    title: "Mere Christianity",
    author: "C.S. Lewis",
    genres: JSON.stringify(["Philosophy", "Non-fiction"]),
    rating: 5,
    status: "to-read",
    readingMood: "thought-provoking",
    startDate: "2026-03-25",
    finishDate: "2026-04-10",
    currentPage: 0,
    totalPages: 227,
    pdfPath: null,
    coverImageUrl: null,
    isbn: null,
    journalEntry: "A foundational text for understanding Christian apologetics and the rational case for God's existence. Will be interesting to examine Lewis's moral argument and compare with atheistic counterarguments.",
    keyLessons: JSON.stringify([]),
    favoriteQuotes: JSON.stringify([]),
    aiDiscussion: "Discussion Prompts: 1) How does Lewis's moral argument hold up against modern evolutionary explanations? 2) Strengths and weaknesses of 'Liar, Lunatic, or Lord' trilemma? 3) How might contemporary atheist philosophers respond?",
    aiRecommended: 1,
    place: null,
    createdAt: "2026-03-25T00:25:00.000Z",
    updatedAt: "2026-03-25T00:25:00.000Z",
  },
  {
    id: "book-god-delusion",
    title: "The God Delusion",
    author: "Richard Dawkins",
    genres: JSON.stringify(["Philosophy", "Non-fiction"]),
    rating: 4,
    status: "to-read",
    readingMood: "challenging",
    startDate: "2026-04-09",
    finishDate: "2026-04-25",
    currentPage: 0,
    totalPages: 374,
    pdfPath: null,
    coverImageUrl: null,
    isbn: null,
    journalEntry: "Dawkins approaches the God question from a scientific perspective. Interested in his evolutionary explanations for religion and critique of theistic arguments.",
    keyLessons: JSON.stringify([]),
    favoriteQuotes: JSON.stringify([]),
    aiDiscussion: "Discussion Prompts: 1) How convincing is Dawkins's refutation of the fine-tuning argument? 2) Does his evolutionary explanation actually undermine theism? 3) Scientific vs philosophical dimensions? 4) How might a theologian respond?",
    aiRecommended: 1,
    place: null,
    createdAt: "2026-03-25T00:25:00.000Z",
    updatedAt: "2026-03-25T00:25:00.000Z",
  },
  {
    id: "book-letter-christian-nation",
    title: "Letter to a Christian Nation",
    author: "Sam Harris",
    genres: JSON.stringify(["Philosophy", "Non-fiction"]),
    rating: 3,
    status: "to-read",
    readingMood: "challenging",
    startDate: "2026-03-23",
    finishDate: "2026-03-24",
    currentPage: 0,
    totalPages: 96,
    pdfPath: null,
    coverImageUrl: null,
    isbn: null,
    journalEntry: "A short, direct critique of Christian belief from a secular perspective. Harris is more aggressive than nuanced, but raises important questions about religion's role in society, morality without God, and the problem of evil.",
    keyLessons: JSON.stringify(["Harris argues that religious moderation enables fundamentalism, that morality doesn't require God, and that faith-based reasoning is dangerous in the modern world."]),
    favoriteQuotes: JSON.stringify(["The president of the United States has claimed, on more than one occasion, to be in dialogue with God. If he said that he was talking to God through his hairdryer, this would precipitate a national emergency. I fail to see how the addition of a hairdryer makes the claim more ridiculous or offensive."]),
    aiDiscussion: "Key Discussion Points: 1) Is Harris right that religious moderation provides cover for extremism? 2) How convincing is his evolutionary account of morality? 3) Does he fairly represent Christian theology? 4) Strongest theistic responses to his problem of evil argument?",
    aiRecommended: 1,
    place: null,
    createdAt: "2026-03-25T00:25:00.000Z",
    updatedAt: "2026-03-26T02:17:00.000Z",
  },
  {
    id: "book-reason-for-god",
    title: "The Reason for God: Belief in an Age of Skepticism",
    author: "Timothy Keller",
    genres: JSON.stringify(["Philosophy", "Non-fiction"]),
    rating: 5,
    status: "to-read",
    readingMood: "thought-provoking",
    startDate: "2026-04-26",
    finishDate: "2026-05-15",
    currentPage: 0,
    totalPages: 293,
    pdfPath: null,
    coverImageUrl: null,
    isbn: null,
    journalEntry: "Keller directly addresses modern objections to Christianity. This will provide a contemporary theistic response to many arguments raised by the New Atheists.",
    keyLessons: JSON.stringify([]),
    favoriteQuotes: JSON.stringify([]),
    aiDiscussion: "Discussion Prompts: 1) How does Keller's approach differ from traditional apologetics? 2) Are his responses to the problem of evil philosophically sound? 3) How effectively does he engage with postmodern skepticism? 4) Compare with Lewis and Dawkins.",
    aiRecommended: 1,
    place: null,
    createdAt: "2026-03-25T00:25:00.000Z",
    updatedAt: "2026-03-25T00:25:00.000Z",
  },
  {
    id: "book-ethics-introduction",
    title: "Ethics: A Contemporary Introduction",
    author: "Harry Gensler",
    genres: JSON.stringify(["Philosophy", "Non-fiction"]),
    rating: 5,
    status: "to-read",
    readingMood: "challenging",
    startDate: "2026-05-01",
    finishDate: "2026-05-30",
    currentPage: 0,
    totalPages: 432,
    pdfPath: null,
    coverImageUrl: null,
    isbn: null,
    journalEntry: "A comprehensive overview of ethical theories - from utilitarianism to virtue ethics to divine command theory. This should provide the philosophical foundation for evaluating arguments about abortion, morality, and other issues.",
    keyLessons: JSON.stringify([]),
    favoriteQuotes: JSON.stringify([]),
    aiDiscussion: "Discussion Prompts: 1) Strengths and weaknesses of consequentialist vs. deontological ethics? 2) How do religious and secular ethical frameworks compare? 3) Which theory best handles difficult moral dilemmas? 4) Can we ground objective morality without God?",
    aiRecommended: 1,
    place: null,
    createdAt: "2026-03-25T00:25:00.000Z",
    updatedAt: "2026-03-25T00:25:00.000Z",
  },
  {
    id: "book-thinking-about-god",
    title: "Thinking About God: An Introduction to Theology",
    author: "Gregory E. Ganssle",
    genres: JSON.stringify(["Philosophy", "Non-fiction"]),
    rating: 4,
    status: "to-read",
    readingMood: "thought-provoking",
    startDate: "2026-03-27",
    finishDate: "2026-04-20",
    currentPage: 0,
    totalPages: 256,
    pdfPath: null,
    coverImageUrl: null,
    isbn: null,
    journalEntry: "A systematic introduction to theological concepts and philosophical theology. Should help frame many of the debates I'm reading about.",
    keyLessons: JSON.stringify([]),
    favoriteQuotes: JSON.stringify([]),
    aiDiscussion: "Discussion Prompts: 1) Relationship between faith and reason in theology? 2) How do different conceptions of God's attributes affect theological debates? 3) Major positions on divine foreknowledge and human freedom? 4) How does philosophical theology differ from apologetics?",
    aiRecommended: 1,
    place: null,
    createdAt: "2026-03-25T00:25:00.000Z",
    updatedAt: "2026-03-25T00:25:00.000Z",
  },
  {
    id: "book-god-is-not-great",
    title: "God Is Not Great: How Religion Poisons Everything",
    author: "Christopher Hitchens",
    genres: JSON.stringify(["Philosophy", "Non-fiction"]),
    rating: 4,
    status: "to-read",
    readingMood: "captivating",
    startDate: "2026-03-26",
    finishDate: "2026-04-08",
    currentPage: 0,
    totalPages: 307,
    pdfPath: null,
    coverImageUrl: null,
    isbn: null,
    journalEntry: "Reading this alongside C.S. Lewis to get both sides of the theism-atheism debate. Hitchens is known for his rhetorical power and critiques of religious institutions and beliefs.",
    keyLessons: JSON.stringify([]),
    favoriteQuotes: JSON.stringify([]),
    aiDiscussion: "Discussion Prompts: 1) Does Hitchens successfully distinguish between criticizing religious institutions vs. the concept of God itself? 2) How do his arguments compare with more sophisticated theological responses? 3) Strongest and weakest parts of his case against theism?",
    aiRecommended: 1,
    place: null,
    createdAt: "2026-03-25T00:25:00.000Z",
    updatedAt: "2026-03-25T00:25:00.000Z",
  },
  {
    id: "book-defending-life",
    title: "Defending Life: A Moral and Legal Case Against Abortion Choice",
    author: "Francis J. Beckwith",
    genres: JSON.stringify(["Philosophy", "Non-fiction"]),
    rating: 4,
    status: "to-read",
    readingMood: "challenging",
    startDate: "2026-03-25",
    finishDate: "2026-04-12",
    currentPage: 0,
    totalPages: 304,
    pdfPath: null,
    coverImageUrl: null,
    isbn: null,
    journalEntry: "A philosophical examination of the abortion debate from a pro-life perspective. Interested in the metaphysical arguments about personhood and bodily autonomy.",
    keyLessons: JSON.stringify([]),
    favoriteQuotes: JSON.stringify([]),
    aiDiscussion: "Discussion Prompts: 1) How strong is the substance view of personhood vs. functionalist alternatives? 2) Best pro-choice responses to Beckwith's arguments? 3) How does he handle hard cases? 4) Role of philosophy vs. emotion in this debate?",
    aiRecommended: 1,
    place: null,
    createdAt: "2026-03-25T00:25:00.000Z",
    updatedAt: "2026-03-25T00:25:00.000Z",
  },
  {
    id: "book-defense-of-abortion",
    title: "A Defense of Abortion",
    author: "Judith Jarvis Thomson",
    genres: JSON.stringify(["Philosophy", "Non-fiction"]),
    rating: 4,
    status: "to-read",
    readingMood: "thought-provoking",
    startDate: "2026-04-13",
    finishDate: "2026-04-15",
    currentPage: 0,
    totalPages: 48,
    pdfPath: null,
    coverImageUrl: null,
    isbn: null,
    journalEntry: "Thomson's famous violinist thought experiment. Reading this to understand the strongest pro-choice philosophical arguments, even granting fetal personhood.",
    keyLessons: JSON.stringify([]),
    favoriteQuotes: JSON.stringify([]),
    aiDiscussion: "Discussion Prompts: 1) How analogous is the violinist case to pregnancy? 2) Does Thomson successfully defend abortion even if the fetus is a person? 3) Right to life vs. right to use another's body? 4) How do her arguments interact with parental obligations?",
    aiRecommended: 1,
    place: null,
    createdAt: "2026-03-25T00:25:00.000Z",
    updatedAt: "2026-03-28T16:13:00.000Z",
  },
];

const seedEntries = [
  {
    id: "entry-hd-1",
    bookId: "book-howling-dark",
    title: "Entry 1 \u2014 Chapters 1\u201310 \u00b7 March 26, 2026",
    chapterRange: "1-10",
    thoughts: "Mid-read, chapter 10. This chapter is called Jinan and it's basically Hadrian trying to have an argument with the woman he loves but being too scared to actually have it. He comes in wanting to talk about Bassander and going home, and she shuts it down before it even starts. But what gets me is that Hadrian isn't really angry \u2014 he's scared. Scared she won't care. Scared that their intimacy doesn't translate into her actually being on his side.\n\nShe loves him but she's still a soldier first. The chapter ends with them together but Ruocchio basically writing the eulogy for the relationship in real time. Hadrian is building futures in his head while Jinan is just trying to hold onto the present.",
    keyLessons: JSON.stringify([
      "Loving someone doesn't mean they'll see things your way",
      "Intimacy isn't the same as loyalty or agreement",
      "Sometimes the most honest thing someone can do is stay present with you instead of making promises they can't keep",
    ]),
    favoriteQuotes: JSON.stringify([
      "It was fear I felt, not anger.",
      "It did not last, nor did I. It could not last. But nothing is beautiful because it lasts.",
      "Do you really think I would let them take you from me?",
    ]),
    themesAndIdeas: JSON.stringify(["Love vs loyalty", "Fear of vulnerability", "Impermanence"]),
    characters: JSON.stringify(["Hadrian", "Jinan"]),
    connections: JSON.stringify([]),
    createdAt: "2026-03-26T02:16:00.000Z",
    updatedAt: "2026-03-26T02:16:00.000Z",
  },
  {
    id: "entry-hd-2",
    bookId: "book-howling-dark",
    title: "Entry 2 \u2014 Chapter 12 \u00b7 March 26, 2026",
    chapterRange: "12",
    thoughts: "Chapter 12 is where everything breaks open. Bassander uses the star charts to declare the mission dead. Hadrian fights him for every inch. The philosophical centrepiece is Hadrian's monologue on the stranger \u2014 and then older Hadrian undercuts him: \"How little I knew.\"\n\nThe line that stuck with me most: \"It is strange, is it not, that there are always people such as I? Men who believe the stranger is always more trustworthy than their neighbour?\" That's a real pattern. Then Jinan pulls away. \"We go to Coritani.\" Five words. He forgot to breathe.",
    keyLessons: JSON.stringify([
      "Idealising the stranger at the expense of your neighbour is its own kind of prejudice",
      "Men are men \u2014 not purely good, not purely evil, always products of circumstance",
      "Love and loyalty aren't the same thing",
      "Being right about the wrong thing for the wrong reasons is still dangerous",
    ]),
    favoriteQuotes: JSON.stringify([
      "It is strange, is it not, that there are always people such as I? Men who believe the stranger is always more trustworthy than their neighbour?",
      "They're as good as people! / How little I knew.",
      "We go to Coritani.",
    ]),
    themesAndIdeas: JSON.stringify(["Xenophobia vs naive idealism", "The stranger", "Political loyalty vs personal love"]),
    characters: JSON.stringify(["Hadrian", "Bassander", "Jinan", "Otavia Corvo"]),
    connections: JSON.stringify([]),
    createdAt: "2026-03-26T02:58:00.000Z",
    updatedAt: "2026-03-26T02:58:00.000Z",
  },
  {
    id: "entry-hd-3",
    bookId: "book-howling-dark",
    title: "Entry 3 \u2014 Chapters 13\u201317 \u00b7 March 28, 2026",
    chapterRange: "13-17",
    thoughts: "Chapter 13 opens with Hadrian reciting Gibson's Eight Forms of Obedience. Chapter 14 \u2014 Hadrian recruits Otavia Corvo. \"Mercy that expects repayment is no mercy at all.\" Chapter 15 \u2014 the infiltration. Hadrian lies to Jinan. \"I kissed her, and kissing her... betrayed her.\" Chapter 16 \u2014 waking Tanaran. Chapter 17 \u2014 the hangar fight, the duel with Bassander, and Jinan's final shot. \"Ti abatre.\" Past tense. I loved you.",
    keyLessons: JSON.stringify([
      "Mercy that expects repayment is not mercy; friendship built on debt is not friendship",
      "The eight forms of obedience are a ladder \u2014 knowing which rung you stand on is the work of a lifetime",
      "You can know exactly what you're doing and still be a fool",
      "Bassander was right: Hadrian is not a hero in a story. He goes anyway",
      "The past tense is the cruelest tense. Ti abatre.",
    ]),
    favoriteQuotes: JSON.stringify([
      "There are two sorts of men. One hears an order from his better and obeys. The other sees order in himself and obeys that.",
      "Beware Greeks bearing gifts.",
      "You don't owe me anything. I am asking for your help.",
      "Mercy that expects repayment is no mercy at all, nor is a friendship truly a friendship that stands on debt and gratitude.",
      "This isn't one of your stories. You're not some sort of hero. The Empire's fate is not in your hands. This is not a play.",
      "Ti abatre.",
    ]),
    themesAndIdeas: JSON.stringify(["Obedience and authority", "Mercy vs transaction", "Betrayal as love", "Heroism deconstructed"]),
    characters: JSON.stringify(["Hadrian", "Otavia Corvo", "Bassander Lin", "Jinan", "Tanaran", "Pallino", "Switch"]),
    connections: JSON.stringify([]),
    createdAt: "2026-03-28T04:57:00.000Z",
    updatedAt: "2026-03-28T04:57:00.000Z",
  },
];

export async function seedDatabase() {
  const db = getDb();

  // Check if already seeded
  const existing = db.select().from(books).all();
  if (existing.length > 0) {
    return { seeded: false, message: "Database already has data" };
  }

  for (const book of seedBooks) {
    db.insert(books).values(book as any).run();
  }

  for (const entry of seedEntries) {
    db.insert(journalEntries).values(entry as any).run();
  }

  return { seeded: true, message: `Seeded ${seedBooks.length} books and ${seedEntries.length} journal entries` };
}
